# Generated by Django 3.0.3 on 2020-02-10 10:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangoapp', '0003_auto_20200210_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDat',
            new_name='UserData',
        ),
    ]
