# Generated by Django 3.0.3 on 2020-02-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_comments_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='followings',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
