# Generated by Django 3.0.3 on 2020-02-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_student_followings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='followings',
        ),
        migrations.AddField(
            model_name='userdata',
            name='followings',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
