# Generated by Django 3.0.3 on 2020-02-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_auto_20200213_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='followings',
        ),
    ]
